{
 "title": "Pflanzen",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Feder Calathea",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{friendly_name=\"Feder Calathea Batterie\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Emerald Palm Batterie",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{friendly_name=\"Emerald Palm Batterie\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drachenbaum Batterie",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"entity_id\"] == \"drachenbaum_battery_state\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Ficus Bonsai Batterie",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"entity_id\"] == \"ficus_bonsai_battery_state\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit Pflanzen",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket:\"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"%\" and r._field == \"value\")\n  |> map(fn: (r) => ({\n      r with friendly_name:\n        if r.entity_id == \"moisture_feder_calathea_luftfeuchtigkeit\" or r.entity_id == \"feder_calathea_soil_moisture\" then \"Feder Calathea\"\n        else if r.entity_id == \"moisture_emerald_palm_luftfeuchtigkeit\" or r.entity_id == \"emerald_palm_soil_moisture\" then \"Emerald Palm\"\n        else if r.entity_id == \"drachenbaum_soil_moisture\" then \"Drachenbaum\"\n        else if r.entity_id == \"ficus_bonsai_soil_moisture\" then \"Ficus Bonsai\"\n        else \"Nicht bekannt\"\n    }))\n  |> filter(fn: (r) => r.friendly_name != \"Nicht bekannt\")\n  |> duplicate(column: \"friendly_name\", as: \"_field\")\n  |> group(columns: [\"_field\"])\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  }
 ]
}