{
 "title": "Sensordaten",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Badezimmer Batterie",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{friendly_name=\"Badezimmer Batterie\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flur Batterie",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{friendly_name=\"Flur Batterie\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Küche Batterie",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{friendly_name=\"Küche Batterie\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schlafzimmer Batterie",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{friendly_name=\"Schlafzimmer Batterie\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wohnzimmer Batterie",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{friendly_name=\"Wohnzimmer Batterie\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "b30 = from(bucket:\"sensor_data_30m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"%\" and r._field == \"value\")\n  |> map(fn: (r) => ({\n      r with friendly_name:\n        if r.entity_id == \"lumi_lumi_weather_luftfeuchtigkeit\" then \"Badezimmer\"\n        else if r.entity_id == \"lumi_lumi_weather_luftfeuchtigkeit_2\" then \"Flur\"\n        else if r.entity_id == \"lumi_lumi_weather_luftfeuchtigkeit_3\" then \"Küche\"\n        else if r.entity_id == \"lumi_lumi_weather_luftfeuchtigkeit_4\" then \"Schlafzimmer\"\n        else if r.entity_id == \"lumi_lumi_weather_luftfeuchtigkeit_5\" then \"Wohnzimmer\"\n        else \"Nicht bekannt\"\n    }))\n  |> filter(fn: (r) => r.friendly_name != \"Nicht bekannt\")\n  |> aggregateWindow(every: 6h, fn: mean, createEmpty: false)\n  |> duplicate(column: \"friendly_name\", as: \"_field\")\n  |> group(columns: [\"_field\"])\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n\nb = from(bucket:\"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"%\" and r._field == \"value\")\n  |> map(fn: (r) => ({\n      r with friendly_name:\n        if r.entity_id == \"lumi_lumi_weather_luftfeuchtigkeit\" then \"Badezimmer\"\n        else if r.entity_id == \"lumi_lumi_weather_luftfeuchtigkeit_2\" then \"Flur\"\n        else if r.entity_id == \"lumi_lumi_weather_luftfeuchtigkeit_3\" then \"Küche\"\n        else if r.entity_id == \"lumi_lumi_weather_luftfeuchtigkeit_4\" then \"Schlafzimmer\"\n        else if r.entity_id == \"lumi_lumi_weather_luftfeuchtigkeit_5\" then \"Wohnzimmer\"\n        else \"Nicht bekannt\"\n    }))\n  |> filter(fn: (r) => r.friendly_name != \"Nicht bekannt\")\n  |> duplicate(column: \"friendly_name\", as: \"_field\")\n  |> group(columns: [\"_field\"])\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n\nunion(tables: [b30, b])\n"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "b30 = from(bucket:\"sensor_data_30m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"°C\" and r._field == \"value\")\n  |> map(fn: (r) => ({\n      r with friendly_name:\n        if r.entity_id == \"lumi_lumi_weather_temperatur\" then \"Badezimmer\"\n        else if r.entity_id == \"lumi_lumi_weather_temperatur_2\" then \"Flur\"\n        else if r.entity_id == \"lumi_lumi_weather_temperatur_3\" then \"Küche\"\n        else if r.entity_id == \"lumi_lumi_weather_temperatur_4\" then \"Schlafzimmer\"\n        else if r.entity_id == \"lumi_lumi_weather_temperatur_5\" then \"Wohnzimmer\"\n        else \"Nicht bekannt\"\n    }))\n  |> filter(fn: (r) => r.friendly_name != \"Nicht bekannt\")\n  |> aggregateWindow(every: 6h, fn: mean, createEmpty: false)\n  |> duplicate(column: \"friendly_name\", as: \"_field\")\n  |> group(columns: [\"_field\"])\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n\nb = from(bucket:\"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"°C\" and r._field == \"value\")\n  |> map(fn: (r) => ({\n      r with friendly_name:\n        if r.entity_id == \"lumi_lumi_weather_temperatur\" then \"Badezimmer\"\n        else if r.entity_id == \"lumi_lumi_weather_temperatur_2\" then \"Flur\"\n        else if r.entity_id == \"lumi_lumi_weather_temperatur_3\" then \"Küche\"\n        else if r.entity_id == \"lumi_lumi_weather_temperatur_4\" then \"Schlafzimmer\"\n        else if r.entity_id == \"lumi_lumi_weather_temperatur_5\" then \"Wohnzimmer\"\n        else \"Nicht bekannt\"\n    }))\n  |> filter(fn: (r) => r.friendly_name != \"Nicht bekannt\")\n  |> duplicate(column: \"friendly_name\", as: \"_field\")\n  |> group(columns: [\"_field\"])\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n\nunion(tables: [b30, b])\n"
    }
   ]
  }
 ]
}