# Active overrides only — full commented template is at /etc/lightdm/lightdm.conf

[Seat:*]
greeter-session=pi-greeter-labwc
greeter-hide-users=false
user-session=rpd-labwc
display-setup-script=/usr/share/dispsetup.sh
autologin-user=marvin
autologin-session=rpd-labwc
