services:
  db:
    image: "postgres:15.3"
    container_name: "postgres"
    hostname: "postgres"
    environment:
      POSTGRES_USER: "marvin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "costs"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    restart: unless-stopped

  consul-server:
    image: hashicorp/consul:1.16
    container_name: consul-server
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
      - ./consul/certs/:/consul/config/certs/:ro
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"
    restart: "unless-stopped"

  consul-client:
    image: hashicorp/consul:1.16
    container_name: consul-client
    volumes:
      - ./consul/client.json:/consul/config/client.json:ro
      - ./consul/certs/:/consul/config/certs/:ro
    command: "agent"
    restart: unless-stopped
  
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    hostname: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: marvin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: wildfly_domain
      DOCKER_INFLUXDB_INIT_BUCKET: costs
      INFLUXDB_REPORTING_DISABLED: true
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:10.4.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: marvin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SECURITY_COOKIE_SAMESITE: disabled
      GF_SECURITY_ALLOW_EMBEDDING: true  
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - influxdb

  adapter_application:
    image: localhost:5000/applications:latest
    container_name: adapter_application
    hostname: adapter_application
    environment:
      IMPORTER_IN: /app/import
      IMPORTER_DONE: /app/import/done
      CAMT_DIRECTORY_IN: /app/camt
      CAMT_DIRECTORY_DONE: /app/camt/done  
    volumes:
      - "/home/marvin/camt:/app/camt"
      - "/home/marvin/import:/app/import"  
    ports:
      - "9001:9001"
    restart: unless-stopped

  homeassistant:
    container_name: home_assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/home_assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    network_mode: host

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    hostname: mosquitto
    restart: unless-stopped  
    volumes:
      - /opt/mosquitto:/mosquitto
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    ports:
      - 1885:1883
      - 9005:9001 

  portfolio-performance:
    image: quallenbezwinger/portfolio-performance:0.9
    container_name: portfolio
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - /opt/docker-volumes/pp/config:/config
      - /opt/docker-volumes/pp/workspace:/opt/portfolio/workspace
    environment:
      USER_ID: 0
      GROUP_ID: 0
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      TZ: "Europe/Berlin"

volumes:
  postgres_data:
  influxdb_data:
  grafana_data:
