version: "3.8"
services:
  db:
    image: "postgres:latest"
    container_name: "postgres"
    environment:
      POSTGRES_USER: "marvin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "wildfly_domain"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    restart: "unless-stopped"

  domain-controller:
    image: quay.io/wildfly/wildfly:28.0.1.Final-jdk17
    container_name: "domain-controller"  
    environment:
      POSTGRES_USER: "marvin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "wildfly_domain"
      POSTGRES_HOST: postgres
    ports:
      - "8081:8080"
      - "9991:9990"
    command: >
      sh -c "/opt/jboss/wildfly/bin/add-user.sh -ds -m -u admin -p admin --silent &&
             /opt/jboss/wildfly/bin/domain.sh -b 0.0.0.0 -bmanagement 0.0.0.0 -bprivate $(hostname -i)"
    volumes:
      - /vagrant/domain_controller/domain/configuration/host.xml:/opt/jboss/wildfly/domain/configuration/host.xml
      - /vagrant/domain_controller/domain/configuration/domain.xml:/opt/jboss/wildfly/domain/configuration/domain.xml  
    depends_on:
      - db

  host-1:
    image: quay.io/wildfly/wildfly:28.0.1.Final-jdk17
    container_name: "host-1"
    environment:
      POSTGRES_USER: "marvin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "wildfly_domain"
      POSTGRES_HOST: postgres
    ports:
      - "8082:8080"
      - "9992:9990"
    command: >
      sh -c "/opt/jboss/wildfly/bin/add-user.sh -ds -m -u admin -p admin --silent &&
             /opt/jboss/wildfly/bin/domain.sh -b 0.0.0.0 -bmanagement 0.0.0.0 -bprivate $(hostname -i)"
    volumes:
      - /vagrant/host-1/domain/configuration/host.xml:/opt/jboss/wildfly/domain/configuration/host.xml
    depends_on:
      - db
      - domain-controller  

  host-2:
    image: quay.io/wildfly/wildfly:28.0.1.Final-jdk17
    container_name: "host-2"
    environment:
      POSTGRES_USER: "marvin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "wildfly_domain"
      POSTGRES_HOST: postgres
    ports:
      - "8083:8080"
      - "9993:9990"
    command: >
      sh -c "/opt/jboss/wildfly/bin/add-user.sh -ds -m -u admin -p admin --silent &&
             /opt/jboss/wildfly/bin/domain.sh -b 0.0.0.0 -bmanagement 0.0.0.0 -bprivate $(hostname -i)"
    volumes:
      - /vagrant/host-2/domain/configuration/host.xml:/opt/jboss/wildfly/domain/configuration/host.xml
    depends_on:
      - db
      - domain-controller

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:7.4.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_ENABLE: 'false'
    command: sh -c "sleep 30s && /etc/confluent/docker/run"

volumes:
  postgres_data:

