version: "3.8"
services:
  db:
    image: "postgres:15.3"
    container_name: "postgres"
    hostname: "postgres"
    environment:
      POSTGRES_USER: "marvin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "wildfly_domain"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    restart: unless-stopped

  domain-controller:
    image: localhost:5000/domain-controller:latest
    container_name: "domain-controller"
    hostname: "domain-controller"
    environment:
      POSTGRES_USER: "marvin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "wildfly_domain"
      POSTGRES_HOST: postgres
    ports:
      - "8081:8080"
      - "8443:8443"
      - "9991:9990"
    restart: unless-stopped
    depends_on:
      - db

  host-1:
    image: localhost:5000/host-1:latest
    container_name: "host-1"
    hostname: "host-1"
    environment:
      POSTGRES_USER: "marvin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "wildfly_domain"
      POSTGRES_HOST: postgres
    volumes:
      - "/home/marvin/google:/home/app/google"
    ports:
      - "8444:8444"
    restart: unless-stopped
    depends_on:
      - db
      - domain-controller

  host-2:
    image: localhost:5000/host-2:latest
    container_name: "host-2"
    hostname: "host-2"
    environment:
      POSTGRES_USER: "marvin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "wildfly_domain"
      POSTGRES_HOST: postgres
    volumes:
      - "/home/marvin/google:/home/app/google"
    ports:
      - "8445:8445"
    restart: unless-stopped
    depends_on:
      - db
      - domain-controller

  host-3:
    image: localhost:5000/host-3:latest
    container_name: "host-3"
    hostname: "host-3"
    environment:
      POSTGRES_USER: "marvin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "wildfly_domain"
      POSTGRES_HOST: postgres
    ports:
      - "8446:8446"
    restart: unless-stopped
    depends_on:
      - db
      - domain-controller

  consul-server:
    image: hashicorp/consul:1.16
    container_name: consul-server
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
      - ./consul/certs/:/consul/config/certs/:ro
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"
    restart: "unless-stopped"

  consul-client:
    image: hashicorp/consul:1.16
    container_name: consul-client
    volumes:
      - ./consul/client.json:/consul/config/client.json:ro
      - ./consul/certs/:/consul/config/certs/:ro
    command: "agent"
    restart: unless-stopped
  
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    hostname: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: marvin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: wildfly_domain
      DOCKER_INFLUXDB_INIT_BUCKET: costs
      INFLUXDB_REPORTING_DISABLED: true
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:10.4.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: marvin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SECURITY_COOKIE_SAMESITE: disabled
      GF_SECURITY_ALLOW_EMBEDDING: true  
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - influxdb

  adapter_application:
    image: localhost:5000/adapter_application:latest
    container_name: adapter_application
    hostname: adapter_application
    volumes:
      - "/home/marvin/camt:/app/camt"
      - "/home/marvin/import:/app/import"  
    ports:
      - "9001:9001"
    restart: unless-stopped

  homeassistant:
    container_name: home_assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/home_assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    network_mode: host

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    hostname: mosquitto
    restart: unless-stopped  
    volumes:
      - /opt/mosquitto:/mosquitto
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    ports:
      - 1885:1883
      - 9005:9001 

volumes:
  postgres_data:
  influxdb_data:
  grafana_data:
