{
 "title": "Energieverbrauch",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "Strompreis", "query": "0.3782" }
  ]
 },
 "panels": [
  { "title": "Waschmaschine / Workstation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Waschmaschine",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"tasmota_energy_power_4\"\r\n                        and r._field == \"value\"\r\n                        and r._measurement == \"W\"\r\n            )\r\n  |> map(fn: (r) => ({r with friendly_name: \"Waschmaschine\"}))\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: 1mo, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  "
    }
   ]
  },
  {
   "title": "Workstation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.entity_id == \"tasmota_energy_power_3\"\n                        and r._measurement == \"W\"\n                        and r._field == \"value\"\n            )\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> aggregateWindow(every: 1mo, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Workstation / Trend in Summe",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.entity_id == \"tasmota_energy_power_3\"\n                        and r._measurement == \"W\"\n                        and r._field == \"value\"\n            )\n  |> map(fn: (r) => ({r with friendly_name: \"Workstation\"}))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"friendly_name\"])\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false, timeSrc: \"_start\")\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Kühlschrank / Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kühlschrank",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"entity_id\"] == \"tasmota_energy_power\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"W\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> aggregateWindow(every: 1mo, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Kühlschrank",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"entity_id\"] == \"tasmota_energy_power\" \n            and r[\"_measurement\"] == \"W\" \n            and r[\"_field\"] == \"value\")\n  |> map(fn: (r) => ({r with friendly_name: \"Kühlschrank\"}))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"friendly_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Kühlschrankkosten / Jahr",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"entity_id\"] == \"tasmota_energy_power\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"W\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> aggregateWindow(every: 1mo, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with _value: (((r._value * 24.0) / 1000.0) * ${Strompreis}) * (7.0 * 4.0 * 12.0)}))\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Server",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"entity_id\"] == \"tasmota_energy_power_2\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"W\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> aggregateWindow(every: 1mo, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Server",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"entity_id\"] == \"tasmota_energy_power_2\" \n            and r[\"_measurement\"] == \"W\" \n            and r[\"_field\"] == \"value\")\n  |> map(fn: (r) => ({r with friendly_name: \"Server\"}))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"friendly_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Serverkosten / Jahr",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"entity_id\"] == \"tasmota_energy_power_2\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"W\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> aggregateWindow(every: 1mo, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with _value: (((r._value * 24.0) / 1000.0) * ${Strompreis}) * (7.0 * 4.0 * 12.0)}))\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}