apiVersion: apps/v1
kind: Deployment
metadata:
  name: anki
  labels:
    app: anki
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anki
  template:
    metadata:
      labels:
        app: anki
    spec:
      containers:
        - name: anki
          image: localhost:5000/anki:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ANKI_COLLECTION_PATH
              value: /data/collection.anki2
            - name: SCHEDULE
              value: 0 0 * * *
            - name: ANKI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: anki-credentials
                  key: ANKI_USERNAME
            - name: ANKI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: anki-credentials
                  key: ANKI_PASSWORD
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: local-mount-anki
