apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stock-portfolio-tracker-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    database-username: AgBRCf0SqJGtJCy8j7BooJ5ma0gDDvOGrPo9MP3dGDecxkB3XbXiE/Rgmsfr51MI/BMblFObGMu7EzU7ozWjZ4O80+XtNlcNmrMl+aUDnTS6jPY3umExFGydMYMuLS8a7Y43Ul/+Dys8tu70oWdmrwwmJl80Dl1mSenxfeM0iE15sZaHs2aTfGjms2x9DOECKAl/Cn07AolZJi3l9+SaIeSQAmU3IaTHxsx3ybfcrZJjmNFEl7yqKgOC3uTF/UcvLTwsy9RV2GS6N/nJETPAsRGO0iLpdT1SCesuo0TokKOPNGTC40oPMXT/D6mqPh/VzfuYWfPzHd1W4BEi47lyIl2fuXKxpvUOgGkWKQW3NUGLQ9dfeIzcfmTzMSY1s0LLqMAA6H1jZM6OYXRPw1CrfVXJ+FytZ8E3rut7ll74/oUgD9+1RGgwe1cBNtj6xdmKau2QWXsC3bt+SB7uecBpSiqyMNztlmgXz2o6aUl+qqFANz62AueQRD65KwIO5VD2lYrabQWZHDPtAen7XPlOEuemwXpzc+/W5gxL1TjJ19fj7xelAbwNdbVUuxxjXCmPIcVeDmd2qTfxZ4tp3/xt7XwJnjd0FS7ZDVBFSCdZpZ8obX6LYeNgzj4D/XGYGywQJwm49Vs76sXKVY18ryWmYpvYgHRZ3XbfznoSodSYYl66Jb3pTnsOQdOPK++OeGQTqykHEdsqmLM=
    database-password: AgB2IBZy1V3dgUyPurEdD32ZDzHnXEz9PTrhCA+tF6SUUw/evorjK8j4/AoI16uzgAaeRUpFqxrizCVBV3ipSYggX2Im0vBaAf+NpJMxph4GiGzbak0ENMfIm8LCtZ+FlyA9PO6822Oax6Q1T0u8rgjafE9pTZ+SU5aQYq9fPaLOGtFNGYakm3xnQQWjShdhYTxtOJ86IrIjUDCiY2H4ma3FB5SWVCLEM82gY+Whq0gCcOVyn3YWJRewP0hcHLDVPFS1ETzqdmaY9c7JaMK7tn0Yxcy3E9GE7LMMFsE7t3SB5go434msxLSkJf+XmWlWV9v7ONxXs2U30RggJjgt5dzXObvf6J7Ri13l3Cg8CJrIDoqhc+I6F6P30Wafwth8Jt21MN4OCkO9UUgSRLBdqLUlmBMEoTZpgMuB0grlsMP0CEcGoYCdItvgLDD/8Wj9fbY4zD9Xs9BrGOCS4PmRQm1I1JaVGwT6ZkE+WXAWJbRwX7PLzL5jOwGLm1BnVc5CeUDUsAsMmGji7YUvSkgU5ZHOGIrcvaIipHX9k9yZBUqfm3xl+RaUdLZzzNCKoLt2bK2VOZ3E8P1xy9nJACu0bW7G4+G343x/0vIs4yE30OBmoTZSdG2XAJwKIgKI3aXWNCTisKZ2g2qDcO+KCgahTIVJNVfv+feBcfsRncWq8gIq37HQJd1rkq3mfEl+RSqv35S1H/dl3HMauA==
  template:
    metadata:
      creationTimestamp: null
      name: stock-portfolio-tracker-secrets
      namespace: {{ .Release.Namespace }}
    type: Opaque
