ingressRoute:
  name: kube-test
  namespace: default
  entryPoints:
    - web
  routes:
    prometheus:
      host: prometheus.home-lab.com
      service: kube-prometheus-stack-prometheus
      port: 9090
    grafana:
      host: grafana.home-lab.com
      service: grafana-service
      port: 3000
    influxdb:
      host: influxdb.home-lab.com
      service: influxdb-service
      port: 8086
    frontend:
      host: frontend.home-lab.com
      service: frontend-service
      port: 80
    backend:
      host: backend.home-lab.com
      service: applications-service
      port: 9055
    linkwarden:
      host: linkwarden.home-lab.com
      service: linkwarden
      port: 3000
    wiki:
      host: wiki.home-lab.com
      service: wikijs-service
      port: 3000
    anki:
      host: anki.home-lab.com
      service: anki-service
      port: 8000
    stock:
      host: stock.home-lab.com
      service: stock-portfolio-tracker-service
      port: 8000

ingressRouteArgocd:
  name: argocd
  namespace: argocd
  entryPoints:
    - web
  host: argocd.home-lab.com
  service: argocd-server
  port: 80

ingressRouteTcp:
  name: postgres-tcp-route
  namespace: default
  entryPoints:
    - postgres
  service: postgres-service
  port: 5432
