apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: default
  labels:
    app: grafana
spec:
  config:
    security:
      admin_user: {{ .Values.grafana.adminUser }}
      admin_password: ${GF_SECURITY_ADMIN_PASSWORD}
      cookie_samesite: {{ .Values.grafana.cookieSamesite }}
      allow_embedding: {{ .Values.grafana.allowEmbedding | quote }}
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.grafana.adminPasswordSecret.name }}
                      key: {{ .Values.grafana.adminPasswordSecret.key }}
