apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: default
  labels:
    app: grafana
spec:
  config:
    security:
      admin_user: {{ .Values.grafana.user }}
      admin_password: {{ .Values.grafana.password }}
      cookie_samesite: {{ .Values.grafana.cookieSamesite }}
      allow_embedding: {{ .Values.grafana.allowEmbedding | quote }}
