apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: default
  labels:
    app: grafana
spec:
  config:
    security:
      cookie_samesite: {{ .Values.grafana.cookieSamesite }}
      allow_embedding: {{ .Values.grafana.allowEmbedding | quote }}
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana

