replicaCount: 1

image:
  repository: localhost:5000/anki
  tag: "v1.0.0"
  pullPolicy: Always

pv:
  capacity: 1Gi
  hostPath: /home/marvin/anki-data
  nodeSelector:
    kubernetes.io/hostname: home-server

persistence:
  storageClassName: local-mount
  mountPath: /data

anki:
  collectionPath: /data/collection.anki2
  syncServer: http://localhost:8080
  schedule: "0 * * * *"
  apiBaseUrl: "http://localhost:8000"

containerPort: 8000

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
