{
 "title": "Geld",
 "time": { "from": "2016-12-31T23:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Monatliche Grundkosten",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"costs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"costs\")\n  |> filter(fn: (r) => r[\"costType\"] == \"daily\")\n  |> aggregateWindow(every: 1mo, fn: sum, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Tageskosten",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"costs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"costs\")\n  |> filter(fn: (r) => r[\"costType\"] == \"daily\")"
    }
   ]
  },
  {
   "title": "Monatliche Gesamtkosten",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"costs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"costs\")\n  |> filter(fn: (r) => r[\"costType\"] == \"monthly\")\n  |> aggregateWindow(every: 1mo, fn: sum, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Nettogehalt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"costs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"costs\")\n  |> filter(fn: (r) => r[\"costType\"] == \"salary\")"
    }
   ]
  },
  {
   "title": "Nettojahresgehalt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"costs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"costs\")\n  |> filter(fn: (r) => r[\"costType\"] == \"salary\")\n  |> aggregateWindow(every: 1y, fn: sum, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Jährlicher Gewinn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"costs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"costs\")\n  |> filter(fn: (r) => r[\"costType\"] == \"salary\" or r[\"costType\"] == \"monthly\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"costType\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with difference: r.salary - r.monthly }))\n  |> keep(columns: [\"_time\", \"difference\"])\n  |> aggregateWindow(every: 1y, fn: sum, column: \"difference\", timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Monatlicher Gewinn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"costs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"costs\")\n  |> filter(fn: (r) => r[\"costType\"] == \"salary\" or r[\"costType\"] == \"monthly\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"costType\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with difference: r.salary - r.monthly }))\n  |> keep(columns: [\"_time\", \"difference\"])"
    }
   ]
  }
 ]
}