apiVersion: v1
kind: Service
metadata:
  name: applications-service
  namespace: default
  labels:
    app: applications-service
spec:
  selector:
    app: applications
  ports:
    - name: http-web
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
