{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: applications-service-monitor
  namespace: default
  labels:
    release: {{ .Values.serviceMonitor.releaseLabel }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: applications
    meta.helm.sh/release-namespace: default
spec:
  endpoints:
  - path: {{ .Values.serviceMonitor.path }}
    port: {{ .Values.serviceMonitor.port }}
    scheme: {{ .Values.serviceMonitor.scheme }}
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: applications-service
{{- end }}
