apiVersion: v1
kind: Service
metadata:
  name: applications-service
  namespace: default
  labels:
    app: applications-service
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: applications
    meta.helm.sh/release-namespace: default
spec:
  selector:
    app: applications
  ports:
    - name: http-web
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
