apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: applications-service-monitor
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - path: /actuator/prometheus
    port: http-web
    scheme: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: applications
