apiVersion: v1
kind: Endpoints
metadata:
  name: home-assistant
  namespace: default
subsets:
- addresses:
  - ip: {{ .Values.homeAssistant.ip }}
  ports:
  - name: metrics
    port: {{ .Values.homeAssistant.metricsPort }}
    protocol: TCP
