image:
  repository: localhost:5000/wikijs
  tag: "latest"
  pullPolicy: Always

containerPort: 3000

env:
  dbType: postgres
  dbHost: postgres-service.default.svc.cluster.local
  dbPort: "5432"
  dbUser: wikijs
  dbName: wikijs

pv:
  size: 2Gi
  path: /home/marvin/wikijs
  nodeSelector:
    kubernetes.io/hostname: home-server

persistence:
  storageClassName: local-mount
  mountPath: /data

service:
  port: 3000
  targetPort: 3000

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
    ephemeral-storage: "256Mi"
  limits:
    memory: "1Gi"
    cpu: "500m"
    ephemeral-storage: "512Mi"
