image:
  repository: ghcr.io/requarks/wiki
  tag: "2"
  pullPolicy: Always

containerPort: 3000

env:
  dbType: postgres
  dbHost: postgres-service
  dbPort: "5432"
  dbUser: marvin
  dbName: costs
  port: "3000"

pv:
  size: 2Gi
  path: /home/marvin/wiki
  nodeSelector:
    kubernetes.io/hostname: home-server

persistence:
  storageClassName: local-mount
  mountPath: /data
  size: 2Gi
  volumeName: local-mount-wikijs

service:
  port: 3000
  targetPort: 3000

resources:
  requests:
    memory: "512Mi"
    cpu: "200m"
    ephemeral-storage: "256Mi"
  limits:
    memory: "1Gi"
    cpu: "350m"
    ephemeral-storage: "512Mi"
