apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-postgres-pvc
  namespace: linkwarden
  labels:
    app: linkwarden
spec:
  storageClassName: local-mount
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
