apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
  namespace: default
data:
  Corefile: |
    home-lab.com:53 {
        log
        errors
        health
        file /etc/coredns/zones/home-lab
    }

    .:53 {
        hosts /etc/coredns/blocklist/adblock.hosts {
            reload 30s
            fallthrough
        }
        {{- range .Values.blockedDomains }}
        template IN ANY {{ . }} {
            rcode NXDOMAIN
        }
        {{- end }}
        log
        errors
        health
        prometheus :9153
        cache 30
        forward . {{ .Values.dns.forwarder }}
    }
