apiVersion: apps/v1
kind: Deployment
metadata:
  name: homedns
  namespace: default
  labels:
    app: homedns
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: homedns
  template:
    metadata:
      labels:
        app: homedns
    spec:
      hostNetwork: true
      dnsPolicy: Default
      containers:
        - name: coredns
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args: [ "-conf", "/etc/coredns/Corefile" ]
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
            - name: config-zone
              mountPath: /etc/coredns/zones
            - name: blocklist-volume
              mountPath: /etc/coredns/blocklist
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
              ephemeral-storage: {{ .Values.resources.requests.ephemeralStorage | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
              ephemeral-storage: {{ .Values.resources.limits.ephemeralStorage | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
      volumes:
        - name: config-volume
          configMap:
            name: coredns-config
            items:
              - key: Corefile
                path: Corefile
        - name: config-zone
          configMap:
            name: coredns-zone
        - name: blocklist-volume
          persistentVolumeClaim:
            claimName: local-mount-blocklist
