prometheusDatasource:
  name: Prometheus
  url: http://kube-prometheus-stack-prometheus.default.svc.cluster.local:9090
  access: proxy
  isDefault: false
  type: prometheus
  jsonData:
    pdcInjected: false
    tlsSkipVerify: true

grafana:
  user: marvin
  password: password
  cookieSamesite: Lax
  allowEmbedding: true

influxdbDatasource:
  name: InfluxDB
  url: http://influxdb-service.default.svc.cluster.local:8086
  access: proxy
  type: influxdb
  isDefault: true
  credentialsSecret:
    name: influxdb-credentials
    key: INFLUX_ADMIN_TOKEN
  jsonData:
    defaultBucket: costs
    httpMode: POST
    organization: wildfly_domain
    version: Flux
    tlsSkipVerify: true
  secureJsonData:
    "token": ${INFLUX_ADMIN_TOKEN}
