prometheusDatasource:
  name: Prometheus
  url: http://kube-prometheus-stack-prometheus.default.svc.cluster.local:9090
  access: proxy
  isDefault: false
  type: prometheus
  jsonData:
    pdcInjected: false
    tlsSkipVerify: true

grafana:
  user: marvin
  password: password
  cookieSamesite: Lax
  allowEmbedding: true

influxdbDatasource:
  name: InfluxDB
  url: http://influxdb-service.default.svc.cluster.local:8086
  access: proxy
  type: influxdb
  isDefault: true
  credentialsSecret:
    name: influxdb-credentials
    key: INFLUX_ADMIN_TOKEN
  jsonData:
    defaultBucket: costs
    httpMode: POST
    organization: wildfly_domain
    version: Flux
    tlsSkipVerify: true

dashboardSync:
  image: alpine/git:latest
  schedule: "0 3 * * *"
  grafanaUrl: http://grafana-service.default.svc.cluster.local:3000
  gitUser: grafana-dashboard-sync
  gitEmail: grafana-sync@noreply.local
  gitRepo: github.com/Marvin1912/smart-home-infrastructure.git
  gitBranch: master
  dashboardDir: k8s/charts/grafana/dashboards

