apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  labels:
    app: wikijs
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          env:
            - name: DB_TYPE
              value: {{ .Values.env.dbType | quote }}
            - name: DB_HOST
              value: {{ .Values.env.dbHost | quote }}
            - name: DB_PORT
              value: {{ .Values.env.dbPort | quote }}
            - name: DB_NAME
              value: {{ .Values.env.dbName | quote }}
            - name: DB_USER
              value: {{ .Values.env.dbUser | quote }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: PORT
              value: {{ .Values.env.port | quote }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory | quote }}
              cpu: {{ .Values.resources.requests.cpu | quote }}
              ephemeral-storage: {{ index .Values.resources.requests "ephemeral-storage" | quote }}
            limits:
              memory: {{ .Values.resources.limits.memory | quote }}
              cpu: {{ .Values.resources.limits.cpu | quote }}
              ephemeral-storage: {{ index .Values.resources.limits "ephemeral-storage" | quote }}
          volumeMounts:
            - name: wikijs-data
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: wikijs-data
          persistentVolumeClaim:
            claimName: wikijs-pvc
