apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  namespace: default
  labels:
    app: linkwarden
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      containers:
        - name: linkwarden
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.databaseUrl | quote }}
            - name: NEXTAUTH_URL
              value: {{ .Values.env.nextauthUrl | quote }}
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: linkwarden-credentials
                  key: NEXTAUTH_SECRET
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
              ephemeral-storage: {{ .Values.resources.requests.ephemeral-storage | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
              ephemeral-storage: {{ .Values.resources.limits.ephemeral-storage | quote }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: local-mount-linkwarden
