apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-mount-linkwarden
spec:
  capacity:
    storage: {{ .Values.pv.size }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.persistence.storageClassName }}
  local:
    path: {{ .Values.pv.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.pv.nodeSelector.["kubernetes.io/hostname"] }}
