apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bp-tracker-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    database-username: AgAztMQpCu+1ukvWBnEaLgjM6JOTHltJdtbwQ+W/ESALQ7Cx781emikHWRIwvlanyPe+vyNPkgfhQVgJRBOu+eHU8hEqNKOZq6ciejuKMTlXh6bxL6sGgzABXG/Lf1m8sN3+Z38aeeRc2+Skf01ko3d5Y0FVlG2uCK+1XYXpqr1x5DBZuueGdbVcObC5jgg9skCIa1IgM/o4VOB9kbenAhQc/u3ZBimtLrtsmZ2FsU5ziSaOnjJAo4gyO+s5LQw+izgxvcwPMp3SaluniA634w5D856eTTKPtX4AYTLzFq5K/JZ+o8aLe3gkk2MExjSz3XL71Lh62Htzl9LFYQxS2T7AwU860qBBqW9G0vIRtWvXlkvvF5OBr1rFJpIm/EkHjytRFC8bGJ/AIjI6lZUw4Qu6igIoBVF65WJM2w8sWOvyf2Bv8sBhsoocRi1JUQq6Otttu8VF4KHiLHeTd1L7nGLVDzZl8QiMl7Y+g8QY+eLUTV2vXpW0MWax2hipSbWm9KY89fRQB/bulIcLlqgsdbT8MmhaC8CpgSTtyjpeYmSlg8S1gWah3I+NnIlYJvexT+QHjWB9/eODdGhjW+Nn1KZEwcOSu8GMeDeDxp+vrwclovFs2ppVZnte3jXIZA2U+RnZEHT9M/E+gKCBw1dWGBUm73WoSD+QuxEQ2d1zr0PlKVnzSUCSfAiqhMg/51CWitI5rUcxbJA=
    database-password: AgB6yYboBeFlIeFuL4UcSkYFZVUyRLD14SVJJnDB1X0HKs6NbFI69NAYM7HG7tHfLyzGWbRSpDmWyesGM7OHb6eWEkbEjenyfSNkWQb+kZ/vLA2Ccg/5HxR7fW8bVmEDq+VQKLGbcCNdnsLFYkzXkhxPBV+8oM8YDW0YM0L/DgZT0I283r4QKvWAaewMZzt2NfkVAZl+FFRiNMC009fkBuJX1TKBP9Sski5eIE8cVsCHf8160k1IdT3iDio5hj/w1XeJW5soRnrlbiKfqfHwX21+szVZydE13lnNWH451DXqd0Vqi6glyb4v7JTdDnipeVmiUqn1Yg1DLhpmQemv2SOjNFLtyEY2gBmBPojOzlKDzbebU/eeYI86nUhto7fI+U8TtGdTsAlipbMFVZYIL8NtxPQXJ4Txq2vh4aN8afwWckiKAXej/cir+noO7qyNGYlSE5N131dMEydQmLjC8dCDOUiW97LiZlZw94WoikQNEc0bkLEJtKhEqEmISmjCjmYojJiG6H637g5OriK3yTNy/GxTiPdULa+Uk/xcM74cuISQyVwDyrLN+IAzB3ekFst3sjXBK10sKlBnrbogfxR5+tKk2UaZ/vjhPN5b4w8A1z23r8stqZZlwjB7bZk2tAH8lMjwc7iPOZu2Uw2xH+q+F5qGz0tg57aqMmnB4y0ZpK+KlYjk457dtmnvBvgbwu9xKsvcfVIp0w==
  template:
    metadata:
      creationTimestamp: null
      name: bp-tracker-secrets
      namespace: {{ .Release.Namespace }}
    type: Opaque
