apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: home-lab
  namespace: argocd
spec:
  description: Home Lab applications project
  sourceRepos:
    - 'git@github.com:Marvin1912/smart-home-infrastructure.git'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
