{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "influxdb-token",
    "namespace": "default",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "influxdb-token",
        "namespace": "default",
        "creationTimestamp": null,
        "labels": {
          "app": "grafana",
          "component": "datasource"
        },
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "TOKEN": "AgAg88BBneE5vtG5Hp2L3nPqXMn4lgW5u7k8rjCp/Xl+VLHcsj86CDxslnQ9xXHosWaH+cmX3zZpH+QKnibWU03UT/3mnK4siOlgq/zGWZWTjxYNKpQ56f27ZJrp+Md8mI0XZF5hbwo4lgOvNL2fDB5HRDEcdMzTcwqy0GI47sRlNIR2elmnhr3oWIUxlMbSEwFJOtp/T1LOxaquRA4OtCEtqyyaiyPPdY2u0SzlzavdwHmvyZ62M9yRy7G/mIJm64wGNTO9CpRyWtUxhLtPW1Ap/Pg5G+ObWJqzletP2Ei9ux+sOmTsYO+X1oZICJ1Iqsx/sMRcfyvGqrgAfcHn40fAxKa4AQvBlc0YOSE4cYPGUhMcBZ2BIUenLf4oqXZ+3Fhh0pK7QhqNXkLBJYifuO5k6KL8lGnAp+cRwayjKQ9WWRZ/FhgacQvrR+bvR8mqepj/VFfJXSD09aReyve4zJQiLLPvPORsPGDi2KTPJp+1WXl+hSJy7aXS8PiClYnhha1LGLoBNOsgRDBJTXOYySQI4Ffpqk/20SezybxYjNSzZ+Ma/HxBBKY9rMV+n/RKI8ri72pxH8KtsG2QfM+GUGIs9Hjb9I92muHswoV/bKS4a9Xqrf2o3+QDvne2kjl0MFhNUDhwt/76UA6Khx76pGz3Os1N7OnamH0WJu6cTzuXo6xzVz51o5hrx5cLe1dvD0U8nahcUzBR2ItvxtUSpI/KS/YriDuvSJkruShG1Suk1dP4+4IPUQALyJoGrh0UiRZh59zeateZ0xh7aZo49P6Ce+S5M48E573rwES+GbAW9ZRRPXYovhLh"
    }
  }
}
