apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-pvc
  namespace: default
spec:
  storageClassName: local-mount
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: local-mount-wikijs
