apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-mount-anki
spec:
  capacity:
    storage: {{ .Values.pv.capacity }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-mount
  local:
    path: {{ .Values.pv.hostPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.pv.nodeSelector.[\"kubernetes.io/hostname\"] }}
