
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_iframe:
  influxdb:
    title: "InfluxDB"
    url: "http://192.168.178.29:8086/"
    icon: "mdi:database"
  grafana:
    title: "Grafana"
    url: "http://192.168.178.29:3000/"
    icon: "mdi:graph"
  frontend:
    title: "Frontend"
    url: "http://192.168.178.29:3001/"
    icon: "mdi:abacus"  

influxdb:
  api_version: 2
  ssl: false
  host: 192.168.178.29
  port: 8086
  token: rmz5aaaKYSpgvXSO3C1UFZmXjvtpwI81b7hcMaMJJqOTjvgI82iNAbSsF7fpGIy2fduNDKACQ759cyaiECrulg==
  organization: wildfly_domain 
  bucket: sensor_data
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  include:
    entity_globs:
      - sensor.lumi_lumi_weather_temperatur*
      - sensor.lumi_lumi_weather_luftfeuchtigkeit*
