apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: home-lab
  source:
    repoURL: 'git@github.com:Marvin1912/smart-home-infrastructure.git'
    targetRevision: master
    path: k8s/charts/applications
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: PersistentVolume
      jsonPointers:
        - /spec/claimRef
