apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs
  namespace: argocd
spec:
  project: home-lab
  source:
    repoURL: 'git@github.com:Marvin1912/smart-home-infrastructure.git'
    targetRevision: master
    path: k8s/charts/wikijs
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
