apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup-job
  namespace: default
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: setup
          image: bash:5.2.21
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache curl jq &&
              /scripts/setup_influxdb.sh
          env:
            - name: INFLUX_URL
              value: "http://influxdb-service.default.svc.cluster.local:8086"
            - name: INFLUX_ORG
              value: {{ .Values.influxdb.org | quote }}
            - name: INIT_TOKEN
              value: "rmz5aaaKYSpgvXSO3C1UFZmXjvtpwI81b7hcMaMJJqOTjvgI82iNAbSsF7fpGIy2fduNDKACQ759cyaiECrulg=="
          volumeMounts:
            - name: setup-script
              mountPath: /scripts
      volumes:
        - name: setup-script
          configMap:
            name: influxdb-setup-script
            defaultMode: 0755
