apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # Configure argocd-server to run in insecure mode for Traefik TLS termination
  server.insecure: "{{ .Values.server.insecure | default true }}"
